# A list of devices you want to take the screenshots from
 devices([
    "iPhone 8 Plus",
#   "iPhone 7 Plus",
#   "iPhone SE",
#   "iPhone X",
#   "iPhone 11"
    "iPhone 11 Pro Max",
#   "iPhone Xs Max"
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
 ])

languages([
   "en-US"
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("catchupSnapshotTests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-testing"])

# For more information about all available options run
# fastlane action snapshot
